In [7]:
!pip install tensorflow
 

  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
  Using cached keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
  Using cached opt

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\narra\\anaconda3\\Lib\\site-packages\\tensorflow\\python\\_pywrap_tensorflow_common.dll'
Consider using the `--user` option or check the permissions.



In [8]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
    
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
## Define the vocabulary size
voc_size=10000

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2403, 6189, 4026, 8964],
 [2403, 6189, 4026, 631],
 [2403, 9634, 4026, 8144],
 [1427, 5995, 5342, 4469, 1815],
 [1427, 5995, 5342, 4469, 729],
 [414, 2403, 4292, 4026, 507],
 [5049, 2938, 5964, 4469]]

In [11]:
## word Embedding Representation
 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
 

In [12]:
import numpy as np
 
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
 

[[   0    0    0    0 2403 6189 4026 8964]
 [   0    0    0    0 2403 6189 4026  631]
 [   0    0    0    0 2403 9634 4026 8144]
 [   0    0    0 1427 5995 5342 4469 1815]
 [   0    0    0 1427 5995 5342 4469  729]
 [   0    0    0  414 2403 4292 4026  507]
 [   0    0    0    0 5049 2938 5964 4469]]


In [13]:
## feature representation
dim=10
 

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim, input_shape=(sent_length,)))
model. Compile('adam','mse')

c:\Users\narra\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


AttributeError: 'Sequential' object has no attribute 'Compile'

In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)
 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step


array([[[-0.03140763, -0.01613164, -0.00979221, -0.04577743,
          0.01821539, -0.00552743,  0.03517825, -0.02636257,
         -0.04691839,  0.01727343],
        [-0.03140763, -0.01613164, -0.00979221, -0.04577743,
          0.01821539, -0.00552743,  0.03517825, -0.02636257,
         -0.04691839,  0.01727343],
        [-0.03140763, -0.01613164, -0.00979221, -0.04577743,
          0.01821539, -0.00552743,  0.03517825, -0.02636257,
         -0.04691839,  0.01727343],
        [-0.03140763, -0.01613164, -0.00979221, -0.04577743,
          0.01821539, -0.00552743,  0.03517825, -0.02636257,
         -0.04691839,  0.01727343],
        [-0.01173162, -0.03312166,  0.01688359, -0.0171352 ,
          0.03827765,  0.01898724, -0.04073543,  0.01004436,
          0.00022078, -0.02643726],
        [-0.02243403,  0.01691112,  0.02738852,  0.0353014 ,
         -0.03298204,  0.02387388, -0.04819885, -0.04471809,
          0.00159829,  0.03512296],
        [ 0.00627724,  0.02240571,  0.01793978,  0.0